services:
  - type: web
    name: belatstrap-site
    env: node
    rootDir: website
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

